name: babybip32
description: A BIP32 (https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki) compatible library for Flutter writing by Dart.
version: 1.0.8
homepage: https://github.com/lpreimesberger/bip32-dart


environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pointycastle: ^2.0.0
  hex: ^0.1.2
  bs58check: ^1.0.1

dev_dependencies:
  test: ^1.0.0
